# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KSA_User_Guide.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Users_Guide(object):
    def setupUi(self, Users_Guide):
        Users_Guide.setObjectName("Users_Guide")
        Users_Guide.setWindowModality(QtCore.Qt.NonModal)
        Users_Guide.resize(400, 519)
        self.verticalLayout = QtWidgets.QVBoxLayout(Users_Guide)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Users_Guide)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textBrowser = QtWidgets.QTextBrowser(Users_Guide)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)

        self.retranslateUi(Users_Guide)
        QtCore.QMetaObject.connectSlotsByName(Users_Guide)

    def retranslateUi(self, Users_Guide):
        _translate = QtCore.QCoreApplication.translate
        Users_Guide.setWindowTitle(_translate("Users_Guide", "KSA Program Users Guide"))
        self.label.setText(_translate("Users_Guide", "KSA Program Instructions"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Users_Guide = QtWidgets.QDialog()
    ui = Ui_Users_Guide()
    ui.setupUi(Users_Guide)
    Users_Guide.show()
    sys.exit(app.exec_())
